// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ieuorllhhfahupcavije.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlldW9ybGxoaGZhaHVwY2F2aWplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyOTIxNTMsImV4cCI6MjA2Nzg2ODE1M30.cVHQNxx8wXKa6-lusZu8GtiC3nBjWl41snlu9TM3in8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});